import React from "react";
import StyledJsxRegistry from "./registry";

export const metadata = {
    title: "Crud com qualidade",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="shortcut icon" href="#"></link>
            </head>
            <body>
                <StyledJsxRegistry>{children}</StyledJsxRegistry>
            </body>
        </html>
    );
}
